### PR TITLE
LPS-54505 - update compile-theme task

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

These changes are to account for the new location of themes in bundles.  It will unzip the jar so that the compile-theme task can use the files for building themes.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/4660. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
