### PR TITLE
LPS-54505 - compile-theme changes

### PR DESCRIPTION
**Pull request by peterfellwock**
@rotty3000 these changes have to do with CSS bundle. They need reviewed and merged in unison @mjbradford89.

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:retest

**Comment by rotty3000** [comment]
Hey Peter can you get this all on one branch with the other css work
please? Getting this in piecemeal will be really hard for me and
@brianchandotcom

**Comment by mjbradford89** [comment]
Hey @rotty3000 
I'm not sure if it's possible to get it all in one pull because there are changes to liferay-plugins and liferay-portal.  We are trying to get the pull request tester to use the updated plugins sdk, but right now we're having problems.

@peterfellwock It looks like the changes I sent you didn't get merged right.  It's including both commits and all changes instead of just the latest.  We should probably close this and the liferay-portal pull and try again.

**Comment by peterfellwock** [comment]
This is getting messy. Closing and starting a new one.

**Pull request closed without merging**
