### PR TITLE
[TECHNICAL-SUPPORT] LPS-59212

### PR DESCRIPTION
**Pull request by jonathanmccann**
Related to https://github.com/rotty3000/liferay-portal/pull/1025

/cc @BryanEngler @arbetts

### CODE REVIEW

**Comment by arbetts** [comment]
@rotty3000 

will you be forwarding this to BChan re: https://github.com/brianchandotcom/liferay-portal/pull/31068

**Comment by arbetts** [comment]
@rotty3000 

any update on this? should i send to someone else?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
It doesn't rebase cleanly. Can you rebase it please?

**Comment by arbetts** [comment]
@rotty3000 

working on the rebase

**Comment by arbetts** [comment]
@rotty3000 

looks like BChan already merged the service builder jar and regen, i'm looking to see what changes i need to make since that's already committed

**Comment by arbetts** [comment]
i updated my original pull and it did not reflect here.

sending a new pull

**Pull request closed without merging**
